title: <p align="center"> Johannes Mäkinen </p>

logo: "/images/picture.png?raw=false"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/johmakinen/">LinkedIn</a> |
  <a href="https://github.com/johmakinen">GitHub</a>
  </p>
  
  <p align="justify">
  I am finishing my Masters in Mathematics and Operations Research at Aalto University, Finland.
  <br><br>
  Currently I am an Analyst at Terveystalo, focusing on Revenue Management and Customer steering.
  <br><br>
  Topics (buzzwords) that I've studied and am interested in
  <ul>
	<li>Statistical inference</li>
	<li>Machine Learning     </li>
	<li>Optimization         </li>
	<li>Clustering           </li>
	<li>Classification       </li>
	<li>Portfolio Optimization</li>
	<li>Regression techniques</li>
	<li>Decision Analysis    </li>
	<li>Time series analysis </li>
	<li>Information visualization</li>
	<li>Bayesian statistics  </li>
	<li>High Performance Computing</li>
	<li>Data Mining          </li>
  </ul>
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
