title: <p align="center"> Johannes Mäkinen </p>

logo: "/images/picture.png?raw=false"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/johmakinen/">LinkedIn</a> |
  <a href="https://github.com/johmakinen">GitHub</a>
  </p>
  
  <p align="left">
  M.Sc. (Tech.) in Mathematics and Operations Research, with an interest in machine learning and data science.
  <br><br>
  Currently, I am an Analyst at Terveystalo, focusing on Revenue Management and Customer steering. In addition, utilising process mining and modelling patient care pathways to highlight potential improvements in treatment effectiveness.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
